### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by berot3** [HananoshikaYomaru/obsidian-custom-save#1]
Hi! 😄

Just wanted to leave a comment regarding

> This plugin is so simple that it probably doesn't need any documentation

You are probably right, but some might want to see what it does without starring at pictures 😄 and that before installing it. The Readme is there to give a good first impression. Tell something about the plugin and who needs and why! 

Keep it going, I like your plugins 😎👍🏻

**Comment by HananoshikaYomaru** [comment]
@berot3 Thanks for your encouragement. I believe I already state the purpose of the plugin in the first line of readme, combining the photos and youtube video, should be enough for people to understand.
